name: CI

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm@7.28.0
          pnpm install

      - name: Install ESLint
        run: |
          pnpm add -D eslint@8.47.0
          pnpm add -D @microsoft/eslint-formatter-sarif@2.1.7

      - name: Build
        run: pnpm run build

      - name: Run ESLint
        run:
          pnpm dlx eslint ./src --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
